#!/bin/sh

rm -f *.opk

make clean
make -f Makefile.funkey
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip clock

cp ./clock opk/

mksquashfs ./opk clock_funkey-s.opk -all-root -noappend -no-exports -no-xattrs

rm -f opk/clock
